apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- dashboard-sa.yaml
- dashboard-ingress.yaml
- https://raw.githubusercontent.com/kubernetes/dashboard/master/charts/recommended.yaml
- grafana.yaml
- loki.yaml
- namespaces.yaml
- prometheus.yaml