apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: counting-app
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: {{ .Values.ingress.hosts }}
      http:
        paths:
          - path: /counting-app
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.nginx.name }}
                port:
                  number: 80