apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: counting-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/default-ssl-certificate: "default/default-tls"
  labels:
    app.kubernetes.io/name: {{ .Values.labels.configmap.name }}
    app.kubernetes.io/version: {{ .Values.labels.configmap.version }}
    app.kubernetes.io/instance: {{ .Values.labels.configmap.instance }}
    app.kubernetes.io/managed-by: {{ .Values.labels.configmap.managed }}
    app.kubernetes.io/component: {{ .Values.labels.configmap.component }}
    app.kubernetes.io/part-of: {{ .Values.labels.configmap.part }}
spec:
  ingressClassName: nginx
  tls:
    - secretName: default-tls
      hosts:
        - {{ .Values.ingress.hosts }}
  rules:
    - host: {{ .Values.ingress.hosts }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.nginx.name }}
                port:
                  number: 80