apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.labels.service.name }}
    app.kubernetes.io/version: {{ .Values.labels.service.version }}
    app.kubernetes.io/instance: {{ .Values.labels.service.instance }}
    app.kubernetes.io/managed-by: {{ .Values.labels.service.managed }}
    app.kubernetes.io/component: {{ .Values.labels.service.component }}
    app.kubernetes.io/part-of: {{ .Values.labels.service.part }}
spec:
  type: {{ .Values.nginx.type }}
  ports:
    - name: http
      port: {{ .Values.nginx.http.port }}
      targetPort: {{ .Values.nginx.http.targetPort }}
      nodePort: {{ .Values.nginx.http.nodePort }}
    - name: https
      port: {{ .Values.nginx.https.port }}
      targetPort: {{ .Values.nginx.https.targetPort }}
      nodePort: {{ .Values.nginx.https.nodePort }}
  selector:
    app: {{ .Values.app.name }}

